/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResponsibilitiesRouteImport } from './routes/responsibilities'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HealthPrepRouteImport } from './routes/health-prep'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as GroceriesRouteImport } from './routes/groceries'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DepartureRouteImport } from './routes/departure'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommsRouteImport } from './routes/comms'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as CalmRouteImport } from './routes/calm'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibilitiesRoute = ResponsibilitiesRouteImport.update({
  id: '/responsibilities',
  path: '/responsibilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthPrepRoute = HealthPrepRouteImport.update({
  id: '/health-prep',
  path: '/health-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceriesRoute = GroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartureRoute = DepartureRouteImport.update({
  id: '/departure',
  path: '/departure',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommsRoute = CommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const CalmRoute = CalmRouteImport.update({
  id: '/calm',
  path: '/calm',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/autopilot': typeof AutopilotRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/calm': typeof CalmRoute
  '/capture': typeof CaptureRoute
  '/checklists': typeof ChecklistsRoute
  '/comms': typeof CommsRoute
  '/compare': typeof CompareRoute
  '/concierge': typeof ConciergeRoute
  '/conflicts': typeof ConflictsRoute
  '/creators': typeof CreatorsRoute
  '/decisions': typeof DecisionsRoute
  '/departure': typeof DepartureRoute
  '/developers': typeof DevelopersRoute
  '/emergency': typeof EmergencyRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/followups': typeof FollowupsRoute
  '/gifts': typeof GiftsRoute
  '/groceries': typeof GroceriesRoute
  '/handoff': typeof HandoffRoute
  '/health-prep': typeof HealthPrepRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/maintenance': typeof MaintenanceRoute
  '/marketplace': typeof MarketplaceRoute
  '/medical': typeof MedicalRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/purchases': typeof PurchasesRoute
  '/readiness': typeof ReadinessRoute
  '/responsibilities': typeof ResponsibilitiesRoute
  '/returns': typeof ReturnsRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/scenarios': typeof ScenariosRoute
  '/school': typeof SchoolRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/twin': typeof TwinRoute
  '/vault': typeof VaultRoute
  '/waiting': typeof WaitingRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/autopilot': typeof AutopilotRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/calm': typeof CalmRoute
  '/capture': typeof CaptureRoute
  '/checklists': typeof ChecklistsRoute
  '/comms': typeof CommsRoute
  '/compare': typeof CompareRoute
  '/concierge': typeof ConciergeRoute
  '/conflicts': typeof ConflictsRoute
  '/creators': typeof CreatorsRoute
  '/decisions': typeof DecisionsRoute
  '/departure': typeof DepartureRoute
  '/developers': typeof DevelopersRoute
  '/emergency': typeof EmergencyRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/followups': typeof FollowupsRoute
  '/gifts': typeof GiftsRoute
  '/groceries': typeof GroceriesRoute
  '/handoff': typeof HandoffRoute
  '/health-prep': typeof HealthPrepRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/maintenance': typeof MaintenanceRoute
  '/marketplace': typeof MarketplaceRoute
  '/medical': typeof MedicalRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/purchases': typeof PurchasesRoute
  '/readiness': typeof ReadinessRoute
  '/responsibilities': typeof ResponsibilitiesRoute
  '/returns': typeof ReturnsRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/scenarios': typeof ScenariosRoute
  '/school': typeof SchoolRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/twin': typeof TwinRoute
  '/vault': typeof VaultRoute
  '/waiting': typeof WaitingRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/autopilot': typeof AutopilotRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/calm': typeof CalmRoute
  '/capture': typeof CaptureRoute
  '/checklists': typeof ChecklistsRoute
  '/comms': typeof CommsRoute
  '/compare': typeof CompareRoute
  '/concierge': typeof ConciergeRoute
  '/conflicts': typeof ConflictsRoute
  '/creators': typeof CreatorsRoute
  '/decisions': typeof DecisionsRoute
  '/departure': typeof DepartureRoute
  '/developers': typeof DevelopersRoute
  '/emergency': typeof EmergencyRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/followups': typeof FollowupsRoute
  '/gifts': typeof GiftsRoute
  '/groceries': typeof GroceriesRoute
  '/handoff': typeof HandoffRoute
  '/health-prep': typeof HealthPrepRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/maintenance': typeof MaintenanceRoute
  '/marketplace': typeof MarketplaceRoute
  '/medical': typeof MedicalRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/purchases': typeof PurchasesRoute
  '/readiness': typeof ReadinessRoute
  '/responsibilities': typeof ResponsibilitiesRoute
  '/returns': typeof ReturnsRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/scenarios': typeof ScenariosRoute
  '/school': typeof SchoolRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/twin': typeof TwinRoute
  '/vault': typeof VaultRoute
  '/waiting': typeof WaitingRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/approvals'
    | '/autopilot'
    | '/bookings'
    | '/calendar'
    | '/calm'
    | '/capture'
    | '/checklists'
    | '/comms'
    | '/compare'
    | '/concierge'
    | '/conflicts'
    | '/creators'
    | '/decisions'
    | '/departure'
    | '/developers'
    | '/emergency'
    | '/expenses'
    | '/family'
    | '/followups'
    | '/gifts'
    | '/groceries'
    | '/handoff'
    | '/health-prep'
    | '/history'
    | '/inbox'
    | '/integrations'
    | '/maintenance'
    | '/marketplace'
    | '/medical'
    | '/onboarding'
    | '/plans'
    | '/predictions'
    | '/privacy'
    | '/providers'
    | '/purchases'
    | '/readiness'
    | '/responsibilities'
    | '/returns'
    | '/review'
    | '/rules'
    | '/scenarios'
    | '/school'
    | '/search'
    | '/security'
    | '/settings'
    | '/sports'
    | '/subscriptions'
    | '/tasks'
    | '/terms'
    | '/travel'
    | '/twin'
    | '/vault'
    | '/waiting'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/approvals'
    | '/autopilot'
    | '/bookings'
    | '/calendar'
    | '/calm'
    | '/capture'
    | '/checklists'
    | '/comms'
    | '/compare'
    | '/concierge'
    | '/conflicts'
    | '/creators'
    | '/decisions'
    | '/departure'
    | '/developers'
    | '/emergency'
    | '/expenses'
    | '/family'
    | '/followups'
    | '/gifts'
    | '/groceries'
    | '/handoff'
    | '/health-prep'
    | '/history'
    | '/inbox'
    | '/integrations'
    | '/maintenance'
    | '/marketplace'
    | '/medical'
    | '/onboarding'
    | '/plans'
    | '/predictions'
    | '/privacy'
    | '/providers'
    | '/purchases'
    | '/readiness'
    | '/responsibilities'
    | '/returns'
    | '/review'
    | '/rules'
    | '/scenarios'
    | '/school'
    | '/search'
    | '/security'
    | '/settings'
    | '/sports'
    | '/subscriptions'
    | '/tasks'
    | '/terms'
    | '/travel'
    | '/twin'
    | '/vault'
    | '/waiting'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/approvals'
    | '/autopilot'
    | '/bookings'
    | '/calendar'
    | '/calm'
    | '/capture'
    | '/checklists'
    | '/comms'
    | '/compare'
    | '/concierge'
    | '/conflicts'
    | '/creators'
    | '/decisions'
    | '/departure'
    | '/developers'
    | '/emergency'
    | '/expenses'
    | '/family'
    | '/followups'
    | '/gifts'
    | '/groceries'
    | '/handoff'
    | '/health-prep'
    | '/history'
    | '/inbox'
    | '/integrations'
    | '/maintenance'
    | '/marketplace'
    | '/medical'
    | '/onboarding'
    | '/plans'
    | '/predictions'
    | '/privacy'
    | '/providers'
    | '/purchases'
    | '/readiness'
    | '/responsibilities'
    | '/returns'
    | '/review'
    | '/rules'
    | '/scenarios'
    | '/school'
    | '/search'
    | '/security'
    | '/settings'
    | '/sports'
    | '/subscriptions'
    | '/tasks'
    | '/terms'
    | '/travel'
    | '/twin'
    | '/vault'
    | '/waiting'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutopilotRoute: typeof AutopilotRoute
  BookingsRoute: typeof BookingsRoute
  CalendarRoute: typeof CalendarRoute
  CalmRoute: typeof CalmRoute
  CaptureRoute: typeof CaptureRoute
  ChecklistsRoute: typeof ChecklistsRoute
  CommsRoute: typeof CommsRoute
  CompareRoute: typeof CompareRoute
  ConciergeRoute: typeof ConciergeRoute
  ConflictsRoute: typeof ConflictsRoute
  CreatorsRoute: typeof CreatorsRoute
  DecisionsRoute: typeof DecisionsRoute
  DepartureRoute: typeof DepartureRoute
  DevelopersRoute: typeof DevelopersRoute
  EmergencyRoute: typeof EmergencyRoute
  ExpensesRoute: typeof ExpensesRoute
  FamilyRoute: typeof FamilyRoute
  FollowupsRoute: typeof FollowupsRoute
  GiftsRoute: typeof GiftsRoute
  GroceriesRoute: typeof GroceriesRoute
  HandoffRoute: typeof HandoffRoute
  HealthPrepRoute: typeof HealthPrepRoute
  HistoryRoute: typeof HistoryRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MedicalRoute: typeof MedicalRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  PredictionsRoute: typeof PredictionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProvidersRoute: typeof ProvidersRoute
  PurchasesRoute: typeof PurchasesRoute
  ReadinessRoute: typeof ReadinessRoute
  ResponsibilitiesRoute: typeof ResponsibilitiesRoute
  ReturnsRoute: typeof ReturnsRoute
  ReviewRoute: typeof ReviewRoute
  RulesRoute: typeof RulesRoute
  ScenariosRoute: typeof ScenariosRoute
  SchoolRoute: typeof SchoolRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SportsRoute: typeof SportsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  TravelRoute: typeof TravelRoute
  TwinRoute: typeof TwinRoute
  VaultRoute: typeof VaultRoute
  WaitingRoute: typeof WaitingRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsibilities': {
      id: '/responsibilities'
      path: '/responsibilities'
      fullPath: '/responsibilities'
      preLoaderRoute: typeof ResponsibilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-prep': {
      id: '/health-prep'
      path: '/health-prep'
      fullPath: '/health-prep'
      preLoaderRoute: typeof HealthPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groceries': {
      id: '/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof GroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departure': {
      id: '/departure'
      path: '/departure'
      fullPath: '/departure'
      preLoaderRoute: typeof DepartureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms': {
      id: '/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof CommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calm': {
      id: '/calm'
      path: '/calm'
      fullPath: '/calm'
      preLoaderRoute: typeof CalmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutopilotRoute: AutopilotRoute,
  BookingsRoute: BookingsRoute,
  CalendarRoute: CalendarRoute,
  CalmRoute: CalmRoute,
  CaptureRoute: CaptureRoute,
  ChecklistsRoute: ChecklistsRoute,
  CommsRoute: CommsRoute,
  CompareRoute: CompareRoute,
  ConciergeRoute: ConciergeRoute,
  ConflictsRoute: ConflictsRoute,
  CreatorsRoute: CreatorsRoute,
  DecisionsRoute: DecisionsRoute,
  DepartureRoute: DepartureRoute,
  DevelopersRoute: DevelopersRoute,
  EmergencyRoute: EmergencyRoute,
  ExpensesRoute: ExpensesRoute,
  FamilyRoute: FamilyRoute,
  FollowupsRoute: FollowupsRoute,
  GiftsRoute: GiftsRoute,
  GroceriesRoute: GroceriesRoute,
  HandoffRoute: HandoffRoute,
  HealthPrepRoute: HealthPrepRoute,
  HistoryRoute: HistoryRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  MaintenanceRoute: MaintenanceRoute,
  MarketplaceRoute: MarketplaceRoute,
  MedicalRoute: MedicalRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  PredictionsRoute: PredictionsRoute,
  PrivacyRoute: PrivacyRoute,
  ProvidersRoute: ProvidersRoute,
  PurchasesRoute: PurchasesRoute,
  ReadinessRoute: ReadinessRoute,
  ResponsibilitiesRoute: ResponsibilitiesRoute,
  ReturnsRoute: ReturnsRoute,
  ReviewRoute: ReviewRoute,
  RulesRoute: RulesRoute,
  ScenariosRoute: ScenariosRoute,
  SchoolRoute: SchoolRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SportsRoute: SportsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  TravelRoute: TravelRoute,
  TwinRoute: TwinRoute,
  VaultRoute: VaultRoute,
  WaitingRoute: WaitingRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
